services:
  - type: web
    name: yfinance-api
    env: python
    plan: starter
    rootDir: .
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -k uvicorn.workers.UvicornWorker main:app --timeout 120"
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
