services:
  - type: web
    name: yfinance-api
    env: python
    plan: starter
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    autoDeploy: true
    envVars:
      - key: pythonVersion
        value: 3.11
